### ISSUE TITLE
GNNs.py

### ISSUE THREAD

**Issue by starry-y** [nju-websoft/AdaLoGN#1]
Hello, thanks for your work !
Is there something wrong in **class RGAT**'s **forward function** of **GNNs.py** ?

In Section2.3.2 of the paper, _(l+1)-th_ iteration is relative directly with _l-th_ iteration. But in the code, I do not see any connections that output in each iteration is individual. Specifically, there are some local variables outside in the code. Should they be put inside the `for` ?
<img width="1065" alt="WechatIMG677" src="https://user-images.githubusercontent.com/57939349/168758186-3cc320cb-9219-4f4e-865a-69c0cf0d438c.png">

**Comment by patronum08** [comment]
Thanks for your attention to our work. The node representations are stored in ‘graph.ndata['h']’. There should be a line '_g.ndata['h'] = h' after line #279 in GNNs.py.
I mistakenly deleted the line for update ’h‘ when I was cleaning up the code for uploading. 
Thank you very much for pointing out this problem in the code. I'll update the code.
'batch_num_nodes' and 'batch_num_edges' will only be used after all iterations.
If you have any other problem, feel free to leave an issue message or send an email to me.

**Comment by patronum08** [comment]
> Thanks for your attention to our work. The node representations are stored in ‘graph.ndata['h']’. There should be a line '_g.ndata['h'] = h' after line #279 in GNNs.py.
> I mistakenly deleted the line for update ’h‘ when I was cleaning up the code for uploading.
> Thank you very much for pointing out this problem in the code. I'll update the code.
> 'batch_num_nodes' and 'batch_num_edges' will only be used after all iterations.
> If you have any other problem, feel free to leave an issue message or send an email to me.

Thanks for your attention to our work. The node representations are stored in ‘graph.ndata['h']’. There should be a line '_g.ndata['h'] = h' after line #279 in GNNs.py.
I mistakenly deleted the line for update ’h‘ when I was cleaning up the code for uploading.
Thank you very much for pointing out this problem in the code. I'll update the code.
'batch_num_nodes' and 'batch_num_edges' will only be used after all iterations.
If you have any other problem, feel free to leave an issue message or send an email to me.

**Comment by patronum08** [comment]
> 

Hi starry-y:
I have updated the code.
Thanks again for pointing out this problem.
Have a good day!
Feel free to reopen it if you have any other questions.

**Comment by starry-y** [comment]
Thank you very much ~!
