### ISSUE TITLE
How long for train?

### ISSUE THREAD

**Issue by zjcanjux** [nju-websoft/AdaLoGN#2]
hello, very valuable work, I train from sctrech, but I find it is very time costing.
batch size is 8, but one step need 13 min! 

  0%|          | 1/2315 [13:20<514:50:48, 800.97s/it]

bert and dgl all in the gpu, 3080ti 12GB. Is it normal for this model?

**Comment by patronum08** [comment]
Thank you for your interest in our work!
It shouldn't take that long. I'm not really sure what caused it. Maybe you can try switching to a GPU with more memory.
If you have more questions, feel free to keep asking me.
Thanks!
